# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d1370d500ab0f3ee470a59ff0e39aed974824d007ac3ba503fa1f72352f79407543b62a90106c25fa59aee7f2a979539fe99d04cf1d79d40cc056aaae768a8e

test:
  secret_key_base: d9d279be286372e5edf799114062fb9e40e0f2127814065d95ab5448c418fa1a42f60f7ca7a74ef7dabff9fe0cc8f3dd2e7733977225b12f28eb7ce100bacce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
